// Package contractor - Automatically generated by cinp-codegen from http://127.0.0.1:8888/api/v1/ at 2024-03-26T14:17:37.955685
package contractor

import (
	"fmt"

	cinp "github.com/cinp/go"
)

// Contractor from http://127.0.0.1:8888/api/v1/
type Contractor struct {
	cinp *cinp.CInP
}

// NewContractor creates and returns a new Contractor
func NewContractor(host string, proxy string) (*Contractor, error) {
	var err error
	s := Contractor{}
	s.cinp, err = cinp.NewCInP(host, "/api/v1/", proxy)
	if err != nil {
		return nil, err
	}

	registerAuth(s.cinp)
	registerBluePrint(s.cinp)
	registerSite(s.cinp)
	registerSurvey(s.cinp)
	registerDirectory(s.cinp)
	registerUtilities(s.cinp)
	registerBuilding(s.cinp)
	registerForeman(s.cinp)
	registerSubContractor(s.cinp)
	registerPostOffice(s.cinp)
	registerRecords(s.cinp)
	registerVirtualBox(s.cinp)
	registerVCenter(s.cinp)
	registerDocker(s.cinp)
	registerIPMI(s.cinp)
	registerManual(s.cinp)
	registerAzure(s.cinp)
	registerAMT(s.cinp)
	registerPacket(s.cinp)
	registerAWS(s.cinp)
	registerRedFish(s.cinp)

	APIVersion, err := s.GetAPIVersion("/api/v1/")
	if err != nil {
		return nil, err
	}

	if APIVersion != "1.0" {
		return nil, fmt.Errorf("API version mismatch.  Got '%s', expected '1.0'", APIVersion)
	}

	return &s, nil
}

// GetAPIVersion Get the API version number for the Namespace at the URI
func (s *Contractor) GetAPIVersion(uri string) (string, error) {
	r, t, err := s.cinp.Describe(uri)
	if err != nil {
		return "", err
	}

	if t != "Namespace" {
		return "", fmt.Errorf("Excpected a Namespace got '%s'", t)
	}

	return r.APIVersion, nil
}

// SetHeader sets a request header
func (s *Contractor) SetHeader(name string, value string) {
	s.cinp.SetHeader(name, value)
}

// ClearHeader clears a request header
func (s *Contractor) ClearHeader(name string) {
	s.cinp.ClearHeader(name)
}
